controller_list:
  - name: fake_robot_1_controller
    type: $(arg execution_type)
    joints:
      - robot_1_shoulder_pan_joint
      - robot_1_shoulder_lift_joint
      - robot_1_elbow_joint
      - robot_1_wrist_1_joint
      - robot_1_wrist_2_joint
      - robot_1_wrist_3_joint
  - name: fake_robot_2_controller
    type: $(arg execution_type)
    joints:
      - robot_2_shoulder_pan_joint
      - robot_2_shoulder_lift_joint
      - robot_2_elbow_joint
      - robot_2_wrist_1_joint
      - robot_2_wrist_2_joint
      - robot_2_wrist_3_joint
  - name: fake_dual_controller
    type: $(arg execution_type)
    joints:
      - robot_1_shoulder_pan_joint
      - robot_1_shoulder_lift_joint
      - robot_1_elbow_joint
      - robot_1_wrist_1_joint
      - robot_1_wrist_2_joint
      - robot_1_wrist_3_joint
      - robot_2_shoulder_pan_joint
      - robot_2_shoulder_lift_joint
      - robot_2_elbow_joint
      - robot_2_wrist_1_joint
      - robot_2_wrist_2_joint
      - robot_2_wrist_3_joint
  - name: fake_gripper_1_controller
    type: $(arg execution_type)
    joints:
      []
  - name: fake_gripper_2_controller
    type: $(arg execution_type)
    joints:
      []
initial:  # Define initial robot poses.
  - group: robot_1
    pose: zero
  - group: robot_2
    pose: zero
  - group: dual
    pose: zero